<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2mka5Nx\Eccube_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2mka5Nx/Eccube_KernelProdContainer.php') {
    touch(__DIR__.'/Container2mka5Nx.legacy');

    return;
}

if (!\class_exists(Eccube_KernelProdContainer::class, false)) {
    \class_alias(\Container2mka5Nx\Eccube_KernelProdContainer::class, Eccube_KernelProdContainer::class, false);
}

return new \Container2mka5Nx\Eccube_KernelProdContainer([
    'container.build_hash' => '2mka5Nx',
    'container.build_id' => 'cea5031f',
    'container.build_time' => 1690947505,
], __DIR__.\DIRECTORY_SEPARATOR.'Container2mka5Nx');
